# Generated by Django 3.0.7 on 2020-07-17 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], max_length=255)),
                ('episode_number', models.IntegerField()),
                ('all_user_average', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchies_name', models.CharField(max_length=255, unique=True)),
                ('franchise_slug', models.SlugField()),
                ('thumb', models.ImageField(blank=True, default='default.png', unique=True, upload_to='')),
                ('film_type', models.BooleanField(default=False)),
                ('film_num', models.IntegerField()),
                ('tv_type', models.BooleanField(default=False)),
                ('tv_num', models.IntegerField()),
                ('oav_type', models.BooleanField(default=False)),
                ('oav_num', models.IntegerField()),
                ('all_user_average', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('number_of_episodes', models.IntegerField()),
                ('all_user_average', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('song_type', models.CharField(choices=[('OP', 'OP'), ('ED', 'ED'), ('OST', 'OST')], max_length=255)),
                ('all_user_average', models.IntegerField()),
                ('franchies_item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.FranchiseItem')),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='MusicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_rate', models.IntegerField()),
                ('song_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Music')),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_average', models.IntegerField()),
                ('user_opinion_average', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FranchiseItemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_average', models.IntegerField()),
                ('user_opinion_average', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('area_type', models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], max_length=255)),
                ('animation_opinion', models.IntegerField()),
                ('story_opinion', models.IntegerField()),
                ('op_num', models.IntegerField()),
                ('ed_num', models.IntegerField()),
                ('music_opinion', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.FranchiseItem')),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpisidesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], max_length=255)),
                ('user_opinion', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('episode_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Episides')),
                ('franchies_item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.FranchiseItem')),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
        ),
        migrations.AddField(
            model_name='episides',
            name='franchies_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.FranchiseItem'),
        ),
        migrations.AddField(
            model_name='episides',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise'),
        ),
        migrations.CreateModel(
            name='AllTVAllSeasonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_average', models.IntegerField()),
                ('user_opinion_average', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllOAVUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_average', models.IntegerField()),
                ('user_opinion_average', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllFilmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_average', models.IntegerField()),
                ('user_opinion_average', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('franchies_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='franchise.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
