# Generated by Django 3.0.7 on 2020-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20200614_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='episides',
            name='all_user_average',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchiseitem',
            name='all_user_average',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='all_user_average',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
