# Generated by Django 3.0.7 on 2020-06-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_auto_20200614_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseitem',
            name='area_name',
        ),
    ]
