# Generated by Django 3.0.7 on 2020-06-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_remove_franchiseitem_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(default='Test'),
            preserve_default=False,
        ),
    ]
