# Generated by Django 3.0.7 on 2020-06-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_franchise_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='slug',
            new_name='franchise_slug',
        ),
    ]
