# Generated by Django 3.0.7 on 2020-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_auto_20200616_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
