# Generated by Django 3.0.7 on 2020-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_franchise_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchies_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
