# Generated by Django 3.0.7 on 2020-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_auto_20200626_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfilmuser',
            name='user_opinion_average',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alloavuser',
            name='user_opinion_average',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alltvallseasonuser',
            name='user_opinion_average',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='franchiseitemuser',
            name='user_opinion_average',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='franchiseuser',
            name='user_opinion_average',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
