# Generated by Django 3.0.7 on 2020-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20200626_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseitemuser',
            name='area_type',
            field=models.CharField(choices=[('Film', 'Film'), ('TV', 'TV'), ('OAV', 'OAV')], default='Film', max_length=255),
            preserve_default=False,
        ),
    ]
