# Generated by Django 3.0.7 on 2020-07-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0013_franchiseitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfilmuser',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allfilmuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='alloavuser',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alloavuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='alltvallseasonuser',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alltvallseasonuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='episides',
            name='franchies_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.FranchiseItem'),
        ),
        migrations.AlterField(
            model_name='episides',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='episidesuser',
            name='episode_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Episides'),
        ),
        migrations.AlterField(
            model_name='episidesuser',
            name='franchies_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.FranchiseItem'),
        ),
        migrations.AlterField(
            model_name='episidesuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='franchiseitem',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='franchiseitem',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='franchiseitemuser',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='franchiseitemuser',
            name='franchies_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.FranchiseItem'),
        ),
        migrations.AlterField(
            model_name='franchiseitemuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='franchiseuser',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='franchiseuser',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='music',
            name='franchies_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.FranchiseItem'),
        ),
        migrations.AlterField(
            model_name='music',
            name='franchies_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Franchise'),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='song_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.Music'),
        ),
    ]
